trigger:
  - master

pool:
  vmImage: "VS2017-Win2016"

variables:
  BuildConfiguration: 'Release'
  AzureSubscriptionEndpoint: 'visual-studio-enterprise'
  WebAppName: learnforcause
  EnvironmentName: learnforcause

stages:
- stage: 'build'
  displayName: 'build'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'build'
    inputs:
      command: publish
      projects: src\web\SelfService\Server\SelfService.Server.csproj
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      displayName: 'Artifacts'
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'

- stage: 'deploy'
  displayName: 'deploy'
  jobs:
  - deployment: 
    pool:
      vmImage: 'vs2017-win2016'
    envionment: '$(EnvironmentName)'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureRMWebAppDeployment@4
              displayName: Azure App service apiVersion
              inputs:
                appType: WebAppNameconnected
                connectedServiceNae: $(AzureSubscriptionEndpoint)
                WebAppName: $(WebAppName)
                Package: $(System.WorkFolder)/**/Server.zip
                UseWebDeploy: true
                DeploymentType: webDeploy


